export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const SIGN_IN_EMAIL = "SIGN_IN_EMAIL";
export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const SIGN_UP_EMAIL = "SIGN_IN_EMAIL";
export const LOGOUT_EMAIL = "LOGOUT_EMAIL";

export const CREATE_TIMELINECARD = 'CREATE_TIMELINECARD'
export const FETCH_TIMELINECARDS = 'FETCH_TIMELINECARDS'
export const FETCH_TIMELINECARD = 'FETCH_TIMELINECARD'
export const DELETE_TIMELINECARD = 'DELETE_TIMELINECARD'
export const EDIT_TIMELINECARD = 'EDIT_TIMELINECARD'

export const CREATE_PUBLICATIONLINECARD = 'CREATE_PUBLICATIONLINECARD'
export const FETCH_PUBLICATIONLINECARDS = 'FETCH_PUBLICATIONLINECARDS'
export const FETCH_PUBLICATIONLINECARD = 'FETCH_PUBLICATIONLINECARD'
export const DELETE_PUBLICATIONLINECARD = 'DELETE_PUBLICATIONLINECARD'
export const EDIT_PUBLICATIONLINECARD = 'EDIT_PUBLICATIONLINECARD'

