export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const SIGN_IN_EMAIL = "SIGN_IN_EMAIL";
export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const SIGN_UP_EMAIL = "SIGN_UP_EMAIL";
export const LOGOUT_EMAIL = "LOGOUT_EMAIL";
export const SIGN_IN_GOOGLE_MAIL = "SIGN_IN_GOOGLE_MAIL";


export const CREATE_TIMELINECARD = 'CREATE_TIMELINECARD'
export const FETCH_TIMELINECARDS = 'FETCH_TIMELINECARDS'
export const FETCH_TIMELINECARD = 'FETCH_TIMELINECARD'
export const DELETE_TIMELINECARD = 'DELETE_TIMELINECARD'
export const EDIT_TIMELINECARD = 'EDIT_TIMELINECARD'
export const SORT_BY_TITLE_TIMELINECARD = 'SORT_BY_TITLE_TIMELINECARD'
export const SORT_BY_DATE_TIMELINECARD = 'SORT_BY_DATE_TIMELINECARD'
export const EDIT_TIMELINECARD_IMG = 'EDIT_TIMELINECARD_IMG'

export const CREATE_PUBLICATIONLINECARD = 'CREATE_PUBLICATIONLINECARD'
export const FETCH_PUBLICATIONLINECARDS = 'FETCH_PUBLICATIONLINECARDS'
export const FETCH_PUBLICATIONLINECARD = 'FETCH_PUBLICATIONLINECARD'
export const DELETE_PUBLICATIONLINECARD = 'DELETE_PUBLICATIONLINECARD'
export const EDIT_PUBLICATIONLINECARD = 'EDIT_PUBLICATIONLINECARD'
export const SORT_BY_TITLE_PUBLICATIONLINECARD = 'SORT_BY_TITLE_PUBLICATIONLINECARD'
export const SORT_BY_DATE_PUBLICATIONLINECARD = 'SORT_BY_DATE_PUBLICATIONLINECARD'
export const EDIT_PUBLICATION_IMG = 'EDIT_PUBLICATION_IMG'

export const CREATE_UTILISATEUR = 'CREATE_UTILISATEUR'
export const FETCH_UTILISATEURS = 'FETCH_UTILISATEURS'
export const FETCH_UTILISATEUR = 'FETCH_UTILISATEUR'
export const DELETE_UTILISATEUR = 'DELETE_UTILISATEUR'
export const EDIT_UTILISATEUR = 'EDIT_UTILISATEUR'
export const EDIT_UTILISATEUR2 = 'EDIT_UTILISATEUR2'
export const SORT_BY_LOGIN_USER = 'SORT_BY_LOGIN_USER'
export const SORT_BY_DATE_USER = 'SORT_BY_DATE_USER'
export const FETCH_UTILISATEUR_LOGIN = 'FETCH_UTILISATEUR_LOGIN'
export const EDIT_UTILISATEURIMG = 'EDIT_UTILISATEURIMG'
export const EDIT_UTILISATEURURLIMG = 'EDIT_UTILISATEURURLIMG'

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const FETCH_QUESTION = 'FETCH_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'

export const DELETE_REPONSE = 'DELETE_REPONSE'






